### ISSUE TITLE
Add elasticsearch_exporter

### ISSUE THREAD

**Issue by simonfrey** [prometheus-community/community#34] opened 2021-04-19 18:04 UTC
We would like to move https://github.com/justwatchcom/elasticsearch_exporter here

It was previously maintained by justwatchcom, but as we currently do not have the capacity to work on it, the repo is kinda abandoned. 

@metalmatze and @SuperQ offered to sponsor this transfer and from our side I am happy to help where I can.

Let's give it some love and get it into a good shape again. Looking forward to your insights.

cc. @zwopir @falschparker82

**Comment by metalmatze** [comment] 2021-04-28 17:41
Hey, 
to push this conversation forward let me tell you about the project itself.
Back in 2017 we were already using the exporter at JustWatch. It was previously created by others in the community and not really maintained at that point. 
Fast-forward to today, I haven't had the need to use the exporter myself since, but I can still see quite some constant activity on the exporter and it'd be amazing to enable the community - most importantly current users - to come together and work on this exporter going forward. 

What do you think @SuperQ?

**Comment by infa-kparida** [comment] 2021-05-04 08:11
This is really super useful exporter when monitoring elasticsearch through prometheus and easy to setup.It will be really helpful if this exporter can get a space here and maintained.

**Comment by infa-kparida** [comment] 2021-05-04 08:14
https://github.com/prometheus-community/community/issues/24 has similar appeal

**Comment by infa-kparida** [comment] 2021-05-09 20:02
Any progress on this ?

**Comment by simonfrey** [comment] 2021-05-10 06:43
@metalmatze Is there anything I can start preparing? I see there is a standard project layout for the repos in this org. 
Where is that documented, so I can morph https://github.com/justwatchcom/elasticsearch_exporter into it? :D

**Comment by roidelapluie** [comment] 2021-05-28 14:16
Duplicate of https://github.com/prometheus-community/community/issues/24

**Comment by roidelapluie** [comment] 2021-05-28 14:16
We should continue the discussion on the original ticket: #24

**Closed by roidelapluie** 2021-05-28 14:16 UTC

**Comment by roidelapluie** [comment] 2021-05-28 14:47
@simonfrey nothing is needed for the transfer. Once transfered, we will do our thing to align it.
